/* Local persistence adapter: replace this module with an API-backed adapter when needed. */
(function(){
  const KEY='goalspace.v1';
  const date=(offset)=>{const d=new Date();d.setDate(d.getDate()+offset);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
  const sample={profile:{name:'Alex Morgan',email:'alex.morgan@example.com',joined:date(-93),bio:'Learning, growing, and taking it one day at a time.'},settings:{dark:false,quote:true,animations:true,reminders:true,accent:'violet'},categories:['Study','Fitness','Finance','Career','Habits','Personal Development','Projects'],goals:[
    {id:'g1',title:'Finish biology course',description:'Complete the online course and consolidate key concepts.',category:'Study',priority:'High',start:date(-32),deadline:date(12),progress:68,status:'Active',milestones:[{id:'m1',title:'Complete modules 1–3',done:true},{id:'m2',title:'Pass practice quiz',done:true},{id:'m3',title:'Finish final modules',done:false}],notes:'Study in focused 45-minute blocks.',habits:['h1'],updated:date(-1),history:[{date:date(-20),progress:35},{date:date(-12),progress:48},{date:date(-5),progress:58},{date:date(-1),progress:68}]},
    {id:'g2',title:'Run a 5K without stopping',description:'Build up endurance with a steady, comfortable training plan.',category:'Fitness',priority:'Medium',start:date(-20),deadline:date(23),progress:42,status:'Active',milestones:[{id:'m4',title:'Run 2 km comfortably',done:true},{id:'m5',title:'Run 3.5 km',done:false},{id:'m6',title:'Complete 5 km',done:false}],notes:'Take recovery days seriously.',habits:['h2'],updated:date(-2),history:[{date:date(-15),progress:15},{date:date(-7),progress:29},{date:date(-2),progress:42}]},
    {id:'g3',title:'Save for a new laptop',description:'Put aside a little each week for a laptop upgrade.',category:'Finance',priority:'Medium',start:date(-45),deadline:date(45),progress:55,status:'Active',milestones:[{id:'m7',title:'Reach first savings target',done:true},{id:'m8',title:'Save half the total',done:true},{id:'m9',title:'Reach full amount',done:false}],notes:'Automate a weekly transfer.',habits:[],updated:date(-3),history:[{date:date(-30),progress:20},{date:date(-14),progress:40},{date:date(-3),progress:55}]},
    {id:'g4',title:'Read 12 books this year',description:'Make reading a relaxing part of the daily routine.',category:'Personal Development',priority:'Low',start:date(-60),deadline:date(94),progress:25,status:'Active',milestones:[{id:'m10',title:'Finish book 3',done:true},{id:'m11',title:'Finish book 6',done:false}],notes:'Keep a book in the bag.',habits:['h1'],updated:date(-4),history:[{date:date(-40),progress:16},{date:date(-4),progress:25}]},
    {id:'g5',title:'Build my portfolio website',description:'Gather projects and publish a simple personal portfolio.',category:'Career',priority:'High',start:date(-65),deadline:date(-5),progress:100,status:'Completed',milestones:[{id:'m12',title:'Choose portfolio pieces',done:true},{id:'m13',title:'Publish first version',done:true}],notes:'Proud of the result!',habits:[],updated:date(-5),history:[{date:date(-30),progress:60},{date:date(-5),progress:100}]}
  ],habits:[{id:'h1',name:'Read for 20 minutes',category:'Personal Development',frequency:'Daily',goalId:'g4',emoji:'📖',checkins:[date(-1),date(-2),date(-3),date(-5),date(-6),date(-7),date(-8),date(-9)]},{id:'h2',name:'Go for a run',category:'Fitness',frequency:'Mon, Wed, Fri',goalId:'g2',emoji:'🏃',checkins:[date(-1),date(-3),date(-5)]},{id:'h3',name:'Review lecture notes',category:'Study',frequency:'Daily',goalId:'g1',emoji:'✍️',checkins:[date(-1),date(-2),date(-4),date(-5)]}],notifications:[{id:'n1',title:'A deadline is coming up',message:'Finish biology course is due in 12 days.',date:date(-1),read:false,type:'deadline'},{id:'n2',title:'Nice work on your streak',message:'You checked in on a habit yesterday. Keep it going!',date:date(-1),read:false,type:'habit'},{id:'n3',title:'Goal completed',message:'You completed Build my portfolio website. Great work!',date:date(-5),read:true,type:'complete'}],achievements:['first-goal','first-milestone','quarter-progress'],activity:[{text:'Completed milestone: Choose portfolio pieces',date:date(-5)},{text:'Reached 68% on Finish biology course',date:date(-1)},{text:'Checked in: Read for 20 minutes',date:date(-1)}],createdAt:date(-93)};
  function load(){try{const raw=localStorage.getItem(KEY);if(!raw){save(sample);return structuredClone(sample)}const parsed=JSON.parse(raw);return {...structuredClone(sample),...parsed}}catch(e){return structuredClone(sample)}}
  function save(data){try{localStorage.setItem(KEY,JSON.stringify(data));return true}catch(e){return false}}
  window.GoalStore={load,save,key:KEY,today:()=>date(0),date};
})();
